import client from 'prom-client';

client.collectDefaultMetrics({ prefix: 'educlip_' });

export const apiResponseTimeHistogram = new client.Histogram({
  name: 'educlip_http_request_duration_seconds',
  help: 'API response time in seconds',
  labelNames: ['method', 'route', 'status_code'],
  buckets: [0.1, 0.3, 0.5, 1, 1.5, 2, 5, 10],
});

export const agentHeartbeatDurationHistogram = new client.Histogram({
  name: 'educlip_agent_heartbeat_duration_seconds',
  help: 'Time taken for heartbeat run to complete',
  labelNames: ['agent_id', 'status'],
  buckets: [1, 5, 10, 30, 60, 120, 300],
});

export const aiTokenGenerationSpeedGauge = new client.Gauge({
  name: 'educlip_ai_token_speed_tps',
  help: 'Tokens per second generated by AI adapters',
  labelNames: ['model', 'agent_id'],
});

export const dbConnectionPoolGauge = new client.Gauge({
  name: 'educlip_db_connection_pool_active',
  help: 'Active connections in DB pool',
});

export const requestCounter = new client.Counter({
  name: 'educlip_http_requests_total',
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'route', 'status_code'],
});

export const getMetrics = async () => {
  return await client.register.metrics();
};
